global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "anime-api"
    static_configs:
      - targets: ["anime-api:3001"]
    metrics_path: "/metrics"

  - job_name: "manga-api"
    static_configs:
      - targets: ["manga-api:3002"]
    metrics_path: "/metrics"
